#########################################
# Enterprise Linux System Health Monitor
#########################################

PROJECT_NAME="Enterprise Linux System Health Monitor"

VERSION="1.0.0"

AUTHOR="Sajid Imran"

REPORT_DIR="../reports"

LOG_DIR="../logs"

DATE_FORMAT="%Y-%m-%d %H:%M:%S"

ENABLE_HTML_REPORT=true

ENABLE_TEXT_REPORT=true

ENABLE_LOGGING=true
